# Generated by Django 5.0 on 2026-08-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Təsvir'),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(choices=[('description', 'Sənəd'), ('assessment', 'Hesabat'), ('apartment', 'Bina/Təşkilat'), ('manage_accounts', 'İdarəçi'), ('gavel', 'Lisenziya'), ('local_shipping', 'Nəqliyyat/Satış'), ('import_export', 'İdxal-İxrac'), ('percent', 'Güzəşt')], default='description', max_length=30, verbose_name='İkon'),
        ),
        migrations.AddField(
            model_name='module',
            name='meta',
            field=models.CharField(blank=True, max_length=100, verbose_name="Əlavə qeyd (məs. 'Müddətsiz')"),
        ),
        migrations.AddField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='permissions_module.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='key',
            field=models.SlugField(max_length=100, verbose_name='Açar'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('parent', 'key')},
        ),
    ]
