# Generated by Django 5.0 on 2026-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions_module', '0002_module_description_module_icon_module_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodulepermission',
            name='can_create',
            field=models.BooleanField(default=False, verbose_name='Yaratma'),
        ),
    ]
