# Generated by Django 6.1 on 2026-08-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tam adı')),
                ('voen', models.CharField(max_length=20, unique=True, verbose_name='VÖEN')),
                ('state_reg_number', models.CharField(blank=True, max_length=50, verbose_name='Dövlət qeydiyyat nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Əsas elektron poçt ünvanı')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Əsas telefon nömrəsi')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Tam ünvan')),
                ('notes', models.TextField(blank=True, verbose_name='Əlavə məlumatlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Təşkilat',
                'verbose_name_plural': 'Təşkilatlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tam adı')),
                ('fin_kod', models.CharField(blank=True, max_length=10, verbose_name='FİN kod')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Departament/Şöbə')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Vəzifə')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron poçt ünvanı')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Əlaqə nömrəsi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_persons', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Səlahiyyətli şəxs',
                'verbose_name_plural': 'Səlahiyyətli şəxslər',
            },
        ),
    ]
