# Generated by Django 5.0 on 2026-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedperson',
            options={'ordering': ['person_type', 'full_name'], 'verbose_name': 'Səlahiyyətli şəxs', 'verbose_name_plural': 'Səlahiyyətli şəxslər'},
        ),
        migrations.AddField(
            model_name='authorizedperson',
            name='person_type',
            field=models.CharField(choices=[('main', 'Əsas'), ('other', 'Digər')], default='main', max_length=10, verbose_name='Növ'),
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(choices=[('msn', 'Müdafiə Sənayesi Nazirliyi'), ('other', 'Digər')], default='other', max_length=20, verbose_name='Kod'),
        ),
    ]
