# Generated by Django 5.0 on 2026-08-26 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationdepartment_organizationposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationdepartment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Müdir'),
        ),
        migrations.AddField(
            model_name='organizationdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Boş buraxılsa, bu ali (top-level) departamentdir. Seçilsə, bu, həmin departamentin daxili strukturu/bölməsidir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.organizationdepartment', verbose_name='Ana departament'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationdepartment',
            unique_together={('organization', 'parent', 'name')},
        ),
    ]
