# Generated by Django 5.0 on 2026-08-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationdepartment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationposition',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='organizationposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organizationposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organizations.organizationdepartment'),
        ),
    ]
