# Generated by Django 5.0 on 2026-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organizationposition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(choices=[('msn', 'Müdafiə Sənayesi Nazirliyi'), ('other', 'Qurum')], default='other', max_length=20, verbose_name='Kod'),
        ),
    ]
