# Generated by Django 5.0 on 2026-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_org_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Şifrəni dəyişməlidir (ilk giriş)'),
        ),
    ]
