# Generated by Django 5.0 on 2026-08-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_backup_codes',
        ),
    ]
