# Generated by Django 5.0 on 2026-08-21 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_totp_backup_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA sıfırlama kodu',
                'verbose_name_plural': '2FA sıfırlama kodları',
            },
        ),
    ]
