# Generated by Django 5.0 on 2026-08-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_totpresetcode'),
        ('organizations', '0004_organizationdepartment_organizationposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Doğum tarixi'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='organizations.organizationdepartment'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='organizations.organizationposition'
            ),
        ),
    ]