# Generated by Django 5.0 on 2026-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_birth_date_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rehber_kadr',
            field=models.BooleanField(default=False, verbose_name='Rəhbər kadr (bütün təşkilatları görə bilər)'),
        ),
    ]
