# Generated by Django 5.0 on 2026-08-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal')], max_length=10, verbose_name='Növ')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Sənəd nömrəsi')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Başlıq')),
                ('submission_mode', models.CharField(choices=[('file', 'Fayl yüklə'), ('form', 'Elektron müraciət forması')], default='file', max_length=10, verbose_name='Müraciət üsulu')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Elektron müraciət forması cavabları')),
                ('applicant_name', models.CharField(blank=True, max_length=255, verbose_name='Müraciətçi müəssisənin tam adı')),
                ('voen', models.CharField(blank=True, max_length=20, verbose_name='VÖEN')),
                ('fin_kod', models.CharField(blank=True, max_length=10, verbose_name='FİN kod')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Departament/Şöbə')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Vəzifə')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon nömrəsi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron poçt ünvanı')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Verilmə tarixi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('status', models.CharField(choices=[('gozleyir', 'Gözlənilir'), ('aktiv', 'Aktiv'), ('bitmis', 'Bitmiş'), ('legv', 'Ləğv edilib'), ('dayandirilib', 'Dayandırılıb')], default='gozleyir', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_documents', to='organizations.authorizedperson')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'İdxal/İxrac icazə sənədi',
                'verbose_name_plural': 'İdxal/İxrac icazə sənədləri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(max_length=100, verbose_name='Sahə açarı')),
                ('field_label', models.CharField(blank=True, max_length=255, verbose_name='Sahə adı')),
                ('file', models.FileField(upload_to='permit_documents/%Y/%m/', verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Orijinal fayl adı')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='licenses.permitdocument')),
            ],
            options={
                'verbose_name': 'İcazə sənədi faylı',
                'verbose_name_plural': 'İcazə sənədi faylları',
            },
        ),
    ]
