# Generated by Django 5.0 on 2026-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdocument',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='Məxfi lisenziya'),
        ),
    ]
