# Generated by Django 5.0 on 2026-08-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_permitdocument_is_confidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal')], max_length=10, verbose_name='Növ'),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('legv', 'Ləğv edilib'), ('dayandirilib', 'Dayandırılıb')], default='gozleyir', max_length=20, verbose_name='Status'),
        ),
    ]
