# Generated by Django 5.0 on 2026-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_permitdocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='status',
            field=models.CharField(choices=[('gozleyir', 'Gözlənilir'), ('aktiv', 'Aktiv'), ('bitmis', 'Bitmiş'), ('legv', 'Ləğv edilib'), ('dayandirilib', 'Dayandırılıb')], default='gozleyir', max_length=20, verbose_name='Status'),
        ),
    ]
