# Generated by Django 5.0 on 2026-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_permitdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış')], max_length=20, verbose_name='Növ'),
        ),
    ]
