# Generated by Django 5.0 on 2026-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_alter_permitdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, verbose_name='Növ'),
        ),
    ]
