# Generated by Django 5.0 on 2026-08-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_alter_permitdocument_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, verbose_name='Növ'),
        ),
    ]
