# Generated by Django 5.0 on 2026-08-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_alter_permitdocument_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permitdocument',
            name='approval_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-ci mərhələ'), (2, '2-ci mərhələ')], default=1, verbose_name='Təsdiq mərhələsi'),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rədd səbəbi'),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage1_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage1_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage1_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage1_comment',
            field=models.TextField(blank=True, verbose_name='1-ci mərhələ qeydi'),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage2_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage2_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage2_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permitdocument',
            name='stage2_comment',
            field=models.TextField(blank=True, verbose_name='2-ci mərhələ qeydi'),
        ),
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staged_approval_enabled', models.BooleanField(default=True, verbose_name='Mərhələli təsdiq aktivdir')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təsdiq tənzimləməsi',
                'verbose_name_plural': 'Təsdiq tənzimləmələri',
            },
        ),
    ]
