# Generated by Django 5.0 on 2026-08-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_permitdocument_approval_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalsettings',
            options={'ordering': ['doc_type'], 'verbose_name': 'Təsdiq tənzimləməsi', 'verbose_name_plural': 'Təsdiq tənzimləmələri'},
        ),
        migrations.AddField(
            model_name='approvalsettings',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], default=1, max_length=20, unique=True, verbose_name='Lisenziya kateqoriyası'),
            preserve_default=False,
        ),
    ]
