# Generated by Django 5.0 on 2026-08-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_alter_approvalsettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Sənəd nömrəsi')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Lisenziya anketi (snapshot)')),
                ('status', models.CharField(choices=[('qaralama', 'Qaralama'), ('tamamlandi', 'Tamamlandı')], default='qaralama', max_length=20, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_certificates', to=settings.AUTH_USER_MODEL)),
                ('permit_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='licenses.permitdocument')),
            ],
            options={
                'verbose_name': 'Lisenziya sənədi',
                'verbose_name_plural': 'Lisenziya sənədləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
