# Generated by Django 5.0 on 2026-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_licensecertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalsettings',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, unique=True, verbose_name='Lisenziya kateqoriyası'),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, verbose_name='Növ'),
        ),
    ]
