# Generated by Django 5.0 on 2026-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0011_alter_approvalsettings_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecertificate',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='İmzalanıb'),
        ),
        migrations.AddField(
            model_name='licensecertificate',
            name='signature_method',
            field=models.CharField(blank=True, choices=[('sim', 'SİM İmza'), ('asan', 'Asan İmza')], max_length=10, verbose_name='İmza üsulu'),
        ),
        migrations.AddField(
            model_name='licensecertificate',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensecertificate',
            name='signed_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='İmza üçün istifadə olunan nömrə'),
        ),
    ]
