# Generated by Django 5.0 on 2026-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_licensecertificate_is_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensecertificate',
            name='signature_method',
            field=models.CharField(blank=True, choices=[('sima', 'SİM İmza'), ('asan', 'Asan İmza')], max_length=10, verbose_name='İmza üsulu'),
        ),
    ]
