# Generated by Django 5.0 on 2026-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0013_alter_licensecertificate_signature_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalsettings',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, unique=True, verbose_name='Lisenziya kateqoriyası'),
        ),
        migrations.AlterField(
            model_name='licensecertificate',
            name='signature_method',
            field=models.CharField(blank=True, choices=[('sim', 'SİM İmza'), ('asan', 'Asan İmza')], max_length=10, verbose_name='İmza üsulu'),
        ),
        migrations.AlterField(
            model_name='permitdocument',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, verbose_name='Növ'),
        ),
    ]
