# Generated by Django 5.0 on 2026-08-18 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_authorizedperson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, verbose_name='Lisenziya kateqoriyası')),
                ('can_approve', models.BooleanField(default=True, verbose_name='Yoxlama və təsdiq hüququ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təsdiq icazəsi (2-ci mərhələ)',
                'verbose_name_plural': 'Təsdiq icazələri (2-ci mərhələ)',
                'ordering': ['user_id', 'doc_type'],
                'unique_together': {('user', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='OrgReviewerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, verbose_name='Lisenziya kateqoriyası')),
                ('can_review', models.BooleanField(default=True, verbose_name='Qurum yoxlaması apara bilər')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_permissions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_reviewer_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qurum yoxlaması icazəsi (1-ci mərhələ)',
                'verbose_name_plural': 'Qurum yoxlaması icazələri (1-ci mərhələ)',
                'ordering': ['organization_id', 'user_id', 'doc_type'],
                'unique_together': {('organization', 'user', 'doc_type')},
            },
        ),
    ]
