# Generated by Django 5.0 on 2026-08-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('edv_guzest', 'ƏDV Güzəşt')], max_length=20, unique=True, verbose_name='Lisenziya kateqoriyası')),
                ('stage1_mode', models.CharField(choices=[('qurum', 'Qurum'), ('msn', 'MSN')], default='qurum', max_length=10, verbose_name='1-ci mərhələ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage1_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='1-ci mərhələ icraçısı (MSN seçildikdə)')),
                ('stage2_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='2-ci mərhələ icraçısı (MSN)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sənəd növü təsdiq axını',
                'verbose_name_plural': 'Sənəd növləri təsdiq axınları',
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('body', models.TextField(blank=True, verbose_name='Mətn')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Keçid (frontend path)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
