# Generated by Django 5.0 on 2026-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_approverpermission_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approverpermission',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, verbose_name='Lisenziya kateqoriyası'),
        ),
        migrations.AlterField(
            model_name='documentworkflowconfig',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, unique=True, verbose_name='Lisenziya kateqoriyası'),
        ),
        migrations.AlterField(
            model_name='orgreviewerpermission',
            name='doc_type',
            field=models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, verbose_name='Lisenziya kateqoriyası'),
        ),
    ]
