# Generated by Django 5.0 on 2026-08-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_authorizedperson_options_and_more'),
        ('workflow', '0005_alter_approverpermission_doc_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgStage2Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ixrac', 'İxrac'), ('idxal', 'İdxal'), ('istehsal', 'İstehsal'), ('xususi_satis', 'Xüsusi Satış'), ('gomrukden_azadolma', 'Gömrükdən Azadolma'), ('edvden_azadolma', 'ƏDV-dən Azadolma')], max_length=20, verbose_name='Lisenziya kateqoriyası')),
                ('skip_stage2', models.BooleanField(default=False, verbose_name='MSN son təsdiqini keçir (2-ci mərhələ söndürülüb)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage2_settings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təşkilat - 2-ci mərhələ tənzimləməsi',
                'verbose_name_plural': 'Təşkilatlar - 2-ci mərhələ tənzimləmələri',
                'ordering': ['organization_id', 'doc_type'],
                'unique_together': {('organization', 'doc_type')},
            },
        ),
    ]
