# Generated by Django 5.0 on 2026-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_orgstage2setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentworkflowconfig',
            name='stage2_enabled',
            field=models.BooleanField(default=True, verbose_name='2-ci mərhələ aktivdir'),
        ),
    ]
