# Generated by Django 5.0 on 2026-08-24 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_documentworkflowconfig_stage2_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentworkflowconfig',
            name='stage1_users',
            field=models.ManyToManyField(blank=True, related_name='workflow_stage1_configs', to=settings.AUTH_USER_MODEL, verbose_name='1-ci mərhələ təsdiqçiləri'),
        ),
        migrations.AlterField(
            model_name='documentworkflowconfig',
            name='stage1_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='1-ci mərhələ icraçısı'),
        ),
    ]
