# Generated by Django 5.0 on 2026-08-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationdepartment_organizationposition'),
        ('workflow', '0008_documentworkflowconfig_stage1_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentworkflowconfig',
            name='stage1_users',
        ),
        migrations.AlterField(
            model_name='documentworkflowconfig',
            name='stage1_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='1-ci mərhələ icraçısı (MSN seçildikdə)'),
        ),
        migrations.CreateModel(
            name='OrganizationStage1Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage1_workflow_configs', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='stage1_organization_workflows', to=settings.AUTH_USER_MODEL, verbose_name='1-ci mərhələ təsdiqçiləri')),
                ('workflow_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_stage1_approvers', to='workflow.documentworkflowconfig')),
            ],
            options={
                'verbose_name': 'Qurum 1-ci mərhələ təsdiqçisi',
                'verbose_name_plural': 'Qurum 1-ci mərhələ təsdiqçiləri',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationstage1approver',
            constraint=models.UniqueConstraint(fields=('workflow_config', 'organization'), name='unique_workflow_organization_stage1'),
        ),
    ]
